/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.OverviewPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author aalnawai
 */
public class ModeButton extends javax.swing.JPanel
{
    private static final long serialVersionUID = 1L;
    private Dimension Icon_Size = new Dimension(20, 15);
    /**
     * Creates new form OverviewButton
     */
    public ModeButton() {

        initComponents();
    }
    public ModeButton(String text) {

        initComponents();
      
    }
    public ImageIcon createResizedIcon(Image img, Dimension size) {
        ImageIcon icon = null;
        Image newimg = img.getScaledInstance(size.width, size.height, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        return icon;
    }
    public static void main(String args[]) {
        JFrame frame = new JFrame("Custom Panels Demo");
        frame.setLayout(new FlowLayout());
        ModeButton standardButton = new ModeButton("Standard Button");
        standardButton.setPreferredSize(new Dimension(130, 28));
        frame.add(standardButton.getButtonsPanel());
        frame.getContentPane().setBackground(Color.WHITE);
        frame.setBackground(Color.WHITE);
        frame.setSize(700, 85);
        frame.setVisible(true);
    }
    public JPanel getButtonsPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
        ModeButton standardButton = new ModeButton("Standard Button");
        standardButton.setPreferredSize(new Dimension(130, 28));


        panel.add(standardButton);

        return panel;

    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowHideButton = new javax.swing.JToggleButton();
        FilterButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(158, 27));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(158, 27));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        ShowHideButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ShowHideButton.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/Intersection.png")).getImage(), Icon_Size));
        ShowHideButton.setText("+");
        ShowHideButton.setMaximumSize(new java.awt.Dimension(35, 35));
        ShowHideButton.setMinimumSize(new java.awt.Dimension(35, 35));
        ShowHideButton.setPreferredSize(new java.awt.Dimension(35, 35));
        ShowHideButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ShowHideButtonStateChanged(evt);
            }
        });
        ShowHideButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ShowHideButtonItemStateChanged(evt);
            }
        });
        add(ShowHideButton);

        FilterButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        FilterButton.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/Filter.png")).getImage(), Icon_Size));
        FilterButton.setText("S");
        FilterButton.setMaximumSize(new java.awt.Dimension(35, 35));
        FilterButton.setMinimumSize(new java.awt.Dimension(35, 35));
        FilterButton.setPreferredSize(new java.awt.Dimension(35, 35));
        add(FilterButton);
    }// </editor-fold>//GEN-END:initComponents
    private void ShowHideButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ShowHideButtonStateChanged
    }//GEN-LAST:event_ShowHideButtonStateChanged
    private void ShowHideButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ShowHideButtonItemStateChanged
        javax.swing.JToggleButton button = (javax.swing.JToggleButton) evt.getSource();
        if (button.isSelected()) {
            setBackground(Color.MAGENTA);
        } else {
            setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_ShowHideButtonItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton FilterButton;
    private javax.swing.JToggleButton ShowHideButton;
    // End of variables declaration//GEN-END:variables
}
