/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SimulationPanel;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author aalnawai
 */
public class Controls extends javax.swing.JPanel
{
    private static final long serialVersionUID = 1L;
    private Color COLOR1 = new Color(255, 255, 255);
    private Color COLOR2 = new Color(115, 201, 29);
    private float pct;
    private String style = "round";
    private static final int OUTER_BEVEL_SIZE = 2;
    private Dimension size = new Dimension(150, 150);
    private Color color = new Color(115, 201, 29);
    private Color pressedColor = null;
    private Color overColor = null;
    private Color selectedColor = null;
    private boolean mouseEntered = false;
    private Dimension Icon_Size = new Dimension(28,28);
    /**
     * Creates new form Controls
     */
    public Controls() {
        super();
        color = new Color(82, 82, 82);
        pressedColor = new Color(161, 64, 0);
        overColor = new Color(115, 201, 29);
        selectedColor = pressedColor;
        setFocusable(false);
       // setPreferredSize(new Dimension(150, 300));
        setForeground(Color.BLACK);
        initComponents();
    }
     public ImageIcon createResizedIcon(Image img, Dimension size) {
        ImageIcon icon = null;
        Image newimg = img.getScaledInstance(size.width, size.height, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        return icon;
    }

    private void paintInsetCircle(Graphics2D graphics, Dimension size, int inset) {
        graphics.fillOval(inset, size.height + 10, size.width - inset * 2, size.height - inset * 2);
    }
    @Override
    public void paintComponent(Graphics g) {
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Color baseColor = color;
//        if (mouseEntered) {
//            GradientPaint outerBevel = new GradientPaint(0.0F, 0.0F, color, 0.0F, size.width + 4, color);
//            //  GradientPaint outerBevel = new GradientPaint(0.0F, 0.0F, new Color(0.0F, 0.0F, 0.0F, 0.25F), 0.0F, size.width + 4, new Color(1.0F, 1.0F, 1.0F, 0.25F));
//            graphics.setPaint(outerBevel);
//             graphics.fillOval(0, 0, size.width , size.height );
//
//
//            GradientPaint outerBevel2 = new GradientPaint(0.0F, 0.0F, new Color(0.0F, 0.0F, 0.0F, 0.25F), 0F, size.width + 4, new Color(1.0F, 1.0F, 1.0F, 0.25F));
//            graphics.setPaint(outerBevel2);
//             graphics.fillOval(0, size.height + 10, size.width , size.height);
//
//        }
//
//        float colorComponents[] = baseColor.getRGBComponents(new float[4]);
//        Color shadowColor = new Color(colorComponents[0] * 0.52F, colorComponents[1] * 0.63F, colorComponents[2] * 0.69F);
//        graphics.setPaint(shadowColor);
//        paintInsetCircle(graphics, totalSize, 2);
//        graphics.setPaint(baseColor);
//        paintInsetCircle(graphics, totalSize, 3);

//        GradientPaint highlight = new GradientPaint(0.0F, 0.0F, new Color(1.0F, 1.0F, 1.0F, 0.25F), 0.0F, (float) totalSize * 0.35F, new Color(1.0F, 1.0F, 1.0F, 0.0F));
//
//        graphics.setPaint(highlight);
//        paintInsetCircle(graphics, totalSize, 4);
//        graphics.setPaint(baseColor);
//        paintInsetCircle(graphics, totalSize, 8);


        super.paintComponent(graphics);

    }
    public static void main(String args[]) {

        JFrame frame = new JFrame("Custom Panels Demo");
        frame.setLayout(new FlowLayout());
        Controls standardButton = new Controls();

 
        standardButton.setPreferredSize(new Dimension(120, 120));


        frame.add(standardButton);

        frame.getContentPane().setBackground(Color.WHITE);
        frame.setBackground(Color.WHITE);
        frame.setSize(700, 180);
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControlUp = new Buttons.CircularButton();
        ControlRight = new Buttons.CircularButton();
        ControlReset = new Buttons.CircularButton();
        ControlLeft = new Buttons.CircularButton();
        ControlRotateLeft = new Buttons.CircularButton();
        ControlDown = new Buttons.CircularButton();
        ControlRotateRight = new Buttons.CircularButton();
        ControlZoomOut = new Buttons.CircularButton();
        ControlZoomIn = new Buttons.CircularButton();
        Control2D = new Buttons.CircularButton();
        Control3D = new Buttons.CircularButton();

        setMaximumSize(new java.awt.Dimension(90, 220));
        setMinimumSize(new java.awt.Dimension(90, 220));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(90, 220));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ControlUp.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Up.png")).getImage(), Icon_Size));
        ControlUp.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlUp.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlUp.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlUp.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Up.png")).getImage(), Icon_Size));
        ControlUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        ControlRight.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Right.png")).getImage(), Icon_Size));
        ControlRight.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRight.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRight.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRight.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Right.png")).getImage(), Icon_Size));
        ControlRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        ControlReset.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Reset.png")).getImage(), Icon_Size));
        ControlReset.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlReset.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlReset.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlReset.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Reset.png")).getImage(), Icon_Size));
        ControlReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        ControlLeft.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Left.png")).getImage(), Icon_Size));
        ControlLeft.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlLeft.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlLeft.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlLeft.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Left.png")).getImage(), Icon_Size));
        ControlLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        ControlRotateLeft.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RotateLeft.png")).getImage(), Icon_Size));
        ControlRotateLeft.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/RotateLeft.png")).getImage(), Icon_Size));
        ControlRotateLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlRotateLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        ControlDown.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Down.png")).getImage(), Icon_Size));
        ControlDown.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlDown.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlDown.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlDown.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Down.png")).getImage(), Icon_Size));
        ControlDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        ControlRotateRight.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RotateRight.png")).getImage(), Icon_Size));
        ControlRotateRight.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/RotateRight.png")).getImage(), Icon_Size));
        ControlRotateRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        add(ControlRotateRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        ControlZoomOut.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/ZoomOut.png")).getImage(), Icon_Size));
        ControlZoomOut.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/ZoomOut.png")).getImage(), Icon_Size));
        add(ControlZoomOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        ControlZoomOut.setVisible(false);

        ControlZoomIn.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/ZoomIn.png")).getImage(), Icon_Size));
        ControlZoomIn.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/ZoomIn.png")).getImage(), Icon_Size));
        add(ControlZoomIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        ControlZoomIn.setVisible(false);

        Control2D.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/2D.png")).getImage(), Icon_Size));
        Control2D.setMaximumSize(new java.awt.Dimension(30, 30));
        Control2D.setMinimumSize(new java.awt.Dimension(30, 30));
        Control2D.setPreferredSize(new java.awt.Dimension(30, 30));
        Control2D.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/2D.png")).getImage(), Icon_Size));
        add(Control2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        Control2D.setVisible(false);

        Control3D.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/3D.png")).getImage(), Icon_Size));
        Control3D.setMaximumSize(new java.awt.Dimension(30, 30));
        Control3D.setMinimumSize(new java.awt.Dimension(30, 30));
        Control3D.setPreferredSize(new java.awt.Dimension(30, 30));
        Control3D.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/3D.png")).getImage(), Icon_Size));
        add(Control3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        Control3D.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents
    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEntered = true;
    }//GEN-LAST:event_formMouseEntered
    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEntered = false;
    }//GEN-LAST:event_formMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Buttons.CircularButton Control2D;
    public Buttons.CircularButton Control3D;
    public Buttons.CircularButton ControlDown;
    public Buttons.CircularButton ControlLeft;
    public Buttons.CircularButton ControlReset;
    public Buttons.CircularButton ControlRight;
    public Buttons.CircularButton ControlRotateLeft;
    public Buttons.CircularButton ControlRotateRight;
    public Buttons.CircularButton ControlUp;
    public Buttons.CircularButton ControlZoomIn;
    public Buttons.CircularButton ControlZoomOut;
    // End of variables declaration//GEN-END:variables
}
