/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.OverviewPanel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author aalnawai
 */
public class OverviewHeaderButton extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private Dimension Icon_Size = new Dimension(20, 15);

    public static enum HeaderMode {

        Add, Select, Navigate
    }

    /**
     * Creates new form OverviewButton
     */
    public OverviewHeaderButton() {
        initComponents();
        Navigation.setSelected(true);
    }
    Color color = null;

    public OverviewHeaderButton(String text) {
        initComponents();
        Navigation.setSelected(true);

    }
    public synchronized boolean IsShowingID(){
        return IDButton.isSelected();
    }

    public synchronized HeaderMode getMode() {
        return (AddButton.isSelected()) ? HeaderMode.Add : (SelectButton.isSelected()) ? HeaderMode.Select : HeaderMode.Navigate;
    }

    public ImageIcon createResizedIcon(Image img, Dimension size) {
        ImageIcon icon = null;
        Image newimg = img.getScaledInstance(size.width, size.height, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        return icon;
    }
   public synchronized JToggleButton getAddButton() {
       return AddButton;
   }
   public synchronized boolean getAddButtonSelectionStatus() {
       return AddButton.isSelected();
   }
   public synchronized void  setAddButtonSelectionStatus(boolean Status) {
        AddButton.setSelected(Status);
   }
   public synchronized JToggleButton getSelectButton() {
       return SelectButton;
   }
   public synchronized boolean getSelectButtonSelectionStatus() {
       return SelectButton.isSelected();
   }
   public synchronized void  setSelectButtonSelectionStatus(boolean Status) {
        SelectButton.setSelected(Status);
   }
   public synchronized JToggleButton getNavigationButton() {
       return Navigation;
   }
   public synchronized boolean getNavigationButtonSelectionStatus() {
       return Navigation.isSelected();
   }
   public synchronized void  setNavigationButtonSelectionStatus(boolean Status) {
        Navigation.setSelected(Status);
   }

    public synchronized JPanel getButtonsPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
        OverviewHeaderButton standardButton = new OverviewHeaderButton("Standard Button");
        standardButton.setPreferredSize(new Dimension(130, 28));
        panel.add(standardButton);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        AddButton = new javax.swing.JToggleButton();
        SelectButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Navigation = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        IDButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(0, 32));
        setMinimumSize(new java.awt.Dimension(0, 32));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 32));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(54, 32));
        jPanel1.setMinimumSize(new java.awt.Dimension(54, 32));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(54, 32));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup1.add(AddButton);
        AddButton.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/Add.png")).getImage(), Icon_Size));
        AddButton.setMaximumSize(new java.awt.Dimension(27, 27));
        AddButton.setMinimumSize(new java.awt.Dimension(27, 27));
        AddButton.setOpaque(true);
        AddButton.setPreferredSize(new java.awt.Dimension(27, 27));
        jPanel1.add(AddButton);

        buttonGroup1.add(SelectButton);
        SelectButton.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/Select.png")).getImage(), new Dimension(30,30)));
        SelectButton.setMaximumSize(new java.awt.Dimension(27, 27));
        SelectButton.setMinimumSize(new java.awt.Dimension(27, 27));
        SelectButton.setOpaque(true);
        SelectButton.setPreferredSize(new java.awt.Dimension(27, 27));
        jPanel1.add(SelectButton);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setMaximumSize(new java.awt.Dimension(54, 32));
        jPanel2.setMinimumSize(new java.awt.Dimension(54, 32));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(54, 32));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(54, 32));
        jPanel3.setMinimumSize(new java.awt.Dimension(54, 32));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(54, 32));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup1.add(Navigation);
        Navigation.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/Navigation.png")).getImage(), Icon_Size));
        Navigation.setMaximumSize(new java.awt.Dimension(27, 27));
        Navigation.setMinimumSize(new java.awt.Dimension(27, 27));
        Navigation.setOpaque(true);
        Navigation.setPreferredSize(new java.awt.Dimension(27, 27));
        jPanel3.add(Navigation);

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        IDButton.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/OverViewPanel/ID.png")).getImage(), Icon_Size));
        IDButton.setMaximumSize(new java.awt.Dimension(27, 27));
        IDButton.setMinimumSize(new java.awt.Dimension(27, 27));
        IDButton.setOpaque(true);
        IDButton.setPreferredSize(new java.awt.Dimension(27, 27));
        jPanel4.add(IDButton);

        add(jPanel4, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AddButton;
    public javax.swing.JToggleButton IDButton;
    private javax.swing.JToggleButton Navigation;
    private javax.swing.JToggleButton SelectButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
