/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SimulationPanel.Utils;
import Buttons.OvalButton;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author aalnawai
 */
public class Controls extends javax.swing.JPanel
{
    private static final long serialVersionUID = 1L;
    private Color COLOR1 = new Color(255, 255, 255);
    private Color COLOR2 = new Color(115, 201, 29);
    private float pct;
    private String style = "round";
    private static final int OUTER_BEVEL_SIZE = 2;
    private Dimension size = new Dimension(150, 150);
    private Color color = new Color(115, 201, 29);
    private Color pressedColor = null;
    private Color overColor = null;
    private Color selectedColor = null;
    private boolean mouseEntered = false;
    private Dimension Icon_Size = new Dimension(28,28);
    /**
     * Creates new form Controls
     */
    public Controls() {
        super();
        color = new Color(82, 82, 82);
        pressedColor = new Color(161, 64, 0);
        overColor = new Color(115, 201, 29);
        selectedColor = pressedColor;
        setFocusable(false);
       // setPreferredSize(new Dimension(150, 300));
        setForeground(Color.BLACK);
        initComponents();
    }
     public ImageIcon createResizedIcon(Image img, Dimension size) {
        ImageIcon icon = null;
        Image newimg = img.getScaledInstance(size.width, size.height, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        return icon;
    }

    private void paintInsetCircle(Graphics2D graphics, Dimension size, int inset) {
        graphics.fillOval(inset, size.height + 10, size.width - inset * 2, size.height - inset * 2);
    }
    @Override
    public void paintComponent(Graphics g) {
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Color baseColor = color;
//        if (mouseEntered) {
//            GradientPaint outerBevel = new GradientPaint(0.0F, 0.0F, color, 0.0F, size.width + 4, color);
//            //  GradientPaint outerBevel = new GradientPaint(0.0F, 0.0F, new Color(0.0F, 0.0F, 0.0F, 0.25F), 0.0F, size.width + 4, new Color(1.0F, 1.0F, 1.0F, 0.25F));
//            graphics.setPaint(outerBevel);
//             graphics.fillOval(0, 0, size.width , size.height );
//
//
//            GradientPaint outerBevel2 = new GradientPaint(0.0F, 0.0F, new Color(0.0F, 0.0F, 0.0F, 0.25F), 0F, size.width + 4, new Color(1.0F, 1.0F, 1.0F, 0.25F));
//            graphics.setPaint(outerBevel2);
//             graphics.fillOval(0, size.height + 10, size.width , size.height);
//
//        }
//
//        float colorComponents[] = baseColor.getRGBComponents(new float[4]);
//        Color shadowColor = new Color(colorComponents[0] * 0.52F, colorComponents[1] * 0.63F, colorComponents[2] * 0.69F);
//        graphics.setPaint(shadowColor);
//        paintInsetCircle(graphics, totalSize, 2);
//        graphics.setPaint(baseColor);
//        paintInsetCircle(graphics, totalSize, 3);

//        GradientPaint highlight = new GradientPaint(0.0F, 0.0F, new Color(1.0F, 1.0F, 1.0F, 0.25F), 0.0F, (float) totalSize * 0.35F, new Color(1.0F, 1.0F, 1.0F, 0.0F));
//
//        graphics.setPaint(highlight);
//        paintInsetCircle(graphics, totalSize, 4);
//        graphics.setPaint(baseColor);
//        paintInsetCircle(graphics, totalSize, 8);


        super.paintComponent(graphics);

    }
    public static void main(String args[]) {

        JFrame frame = new JFrame("Custom Panels Demo");
        frame.setLayout(new FlowLayout());
        Controls standardButton = new Controls();


        standardButton.setPreferredSize(new Dimension(120, 120));


        frame.add(standardButton);

        frame.getContentPane().setBackground(Color.WHITE);
        frame.setBackground(Color.WHITE);
        frame.setSize(700, 180);
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ZoomPanel = new javax.swing.JPanel();
        zoomFactorSlider = new javax.swing.JSlider();
        ControlsPanel = new javax.swing.JPanel();
        ControlUp = new Buttons.CircularButton();
        ControlRight = new Buttons.CircularButton();
        ControlReset = new Buttons.CircularButton();
        ControlLeft = new Buttons.CircularButton();
        ControlRotateLeft = new Buttons.CircularButton();
        ControlDown = new Buttons.CircularButton();
        ControlRotateRight = new Buttons.CircularButton();
        ControlZoomOut = new Buttons.CircularButton();
        ControlZoomIn = new Buttons.CircularButton();
        Control2D = new Buttons.CircularButton();
        Control3D = new Buttons.CircularButton();
        PanningPanel = new javax.swing.JPanel();
        panningFactorSlider = new javax.swing.JSlider();
        PanningPanel1 = new javax.swing.JPanel();
        ZoomingPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanningPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(90, 220));
        jPanel1.setMinimumSize(new java.awt.Dimension(90, 220));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(90, 220));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1formMouseExited(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(90, 220));
        setMinimumSize(new java.awt.Dimension(90, 220));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(90, 220));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        ZoomPanel.setOpaque(false);
        ZoomPanel.setPreferredSize(new java.awt.Dimension(30, 0));
        ZoomPanel.setLayout(new java.awt.BorderLayout());

        zoomFactorSlider.setMajorTickSpacing(10);
        zoomFactorSlider.setMinorTickSpacing(5);
        zoomFactorSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        zoomFactorSlider.setPaintTicks(true);
        zoomFactorSlider.setSnapToTicks(true);
        zoomFactorSlider.setMaximumSize(new java.awt.Dimension(0, 10));
        zoomFactorSlider.setMinimumSize(new java.awt.Dimension(0, 10));
        zoomFactorSlider.setOpaque(false);
        zoomFactorSlider.setPreferredSize(new java.awt.Dimension(0, 10));
        zoomFactorSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zoomFactorSliderStateChanged(evt);
            }
        });
        ZoomPanel.add(zoomFactorSlider, java.awt.BorderLayout.CENTER);

        add(ZoomPanel, java.awt.BorderLayout.WEST);

        ControlsPanel.setMaximumSize(new java.awt.Dimension(0, 40));
        ControlsPanel.setMinimumSize(new java.awt.Dimension(0, 40));
        ControlsPanel.setOpaque(false);
        ControlsPanel.setPreferredSize(new java.awt.Dimension(0, 40));

        ControlUp.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Up.png")).getImage(), Icon_Size));
        ControlUp.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlUp.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlUp.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlUp.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Up.png")).getImage(), Icon_Size));
        ControlUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlRight.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Right.png")).getImage(), Icon_Size));
        ControlRight.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRight.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRight.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRight.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Right.png")).getImage(), Icon_Size));
        ControlRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlReset.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Reset.png")).getImage(), Icon_Size));
        ControlReset.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlReset.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlReset.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlReset.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Reset.png")).getImage(), Icon_Size));
        ControlReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlLeft.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Left.png")).getImage(), Icon_Size));
        ControlLeft.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlLeft.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlLeft.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlLeft.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Left.png")).getImage(), Icon_Size));
        ControlLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlRotateLeft.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RotateLeft.png")).getImage(), Icon_Size));
        ControlRotateLeft.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRotateLeft.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/RotateLeft.png")).getImage(), Icon_Size));
        ControlRotateLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlDown.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/Down.png")).getImage(), Icon_Size));
        ControlDown.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlDown.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlDown.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlDown.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/Down.png")).getImage(), Icon_Size));
        ControlDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlRotateRight.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RotateRight.png")).getImage(), Icon_Size));
        ControlRotateRight.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlRotateRight.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/RotateRight.png")).getImage(), Icon_Size));
        ControlRotateRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ControlZoomOut.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/ZoomOut.png")).getImage(), Icon_Size));
        ControlZoomOut.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlZoomOut.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/ZoomOut.png")).getImage(), Icon_Size));

        ControlZoomIn.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/ZoomIn.png")).getImage(), Icon_Size));
        ControlZoomIn.setMaximumSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setMinimumSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setPreferredSize(new java.awt.Dimension(30, 30));
        ControlZoomIn.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/ZoomIn.png")).getImage(), Icon_Size));

        Control2D.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/2D.png")).getImage(), Icon_Size));
        Control2D.setMaximumSize(new java.awt.Dimension(30, 30));
        Control2D.setMinimumSize(new java.awt.Dimension(30, 30));
        Control2D.setPreferredSize(new java.awt.Dimension(30, 30));
        Control2D.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/2D.png")).getImage(), Icon_Size));

        Control3D.setIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/3D.png")).getImage(), Icon_Size));
        Control3D.setMaximumSize(new java.awt.Dimension(30, 30));
        Control3D.setMinimumSize(new java.awt.Dimension(30, 30));
        Control3D.setPreferredSize(new java.awt.Dimension(30, 30));
        Control3D.setRolloverIcon(createResizedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ControlPanel/RollOver/3D.png")).getImage(), Icon_Size));

        javax.swing.GroupLayout ControlsPanelLayout = new javax.swing.GroupLayout(ControlsPanel);
        ControlsPanel.setLayout(ControlsPanelLayout);
        ControlsPanelLayout.setHorizontalGroup(
            ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControlsPanelLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(ControlUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addComponent(ControlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ControlReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ControlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addComponent(ControlRotateLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ControlDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ControlRotateRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addComponent(ControlZoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Control3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Control2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ControlZoomIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        ControlsPanelLayout.setVerticalGroup(
            ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ControlsPanelLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(ControlUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ControlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ControlReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ControlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ControlRotateLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ControlDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ControlRotateRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(ControlZoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addComponent(Control3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Control2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(ControlZoomIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        //ControlZoomOut.setVisible(false);
        //ControlZoomIn.setVisible(false);
        //Control2D.setVisible(false);
        //Control3D.setVisible(false);

        add(ControlsPanel, java.awt.BorderLayout.CENTER);

        PanningPanel.setOpaque(false);
        PanningPanel.setPreferredSize(new java.awt.Dimension(30, 0));
        PanningPanel.setLayout(new java.awt.BorderLayout());

        panningFactorSlider.setMajorTickSpacing(10);
        panningFactorSlider.setMinorTickSpacing(5);
        panningFactorSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        panningFactorSlider.setPaintTicks(true);
        panningFactorSlider.setSnapToTicks(true);
        panningFactorSlider.setOpaque(false);
        panningFactorSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panningFactorSliderStateChanged(evt);
            }
        });
        PanningPanel.add(panningFactorSlider, java.awt.BorderLayout.CENTER);

        add(PanningPanel, java.awt.BorderLayout.EAST);

        PanningPanel1.setOpaque(false);
        PanningPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        PanningPanel1.setLayout(new java.awt.BorderLayout());

        ZoomingPanel2.setOpaque(false);
        ZoomingPanel2.setPreferredSize(new java.awt.Dimension(50, 30));
        ZoomingPanel2.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Zooming");
        ZoomingPanel2.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Speed");
        ZoomingPanel2.add(jLabel7, java.awt.BorderLayout.SOUTH);

        PanningPanel1.add(ZoomingPanel2, java.awt.BorderLayout.WEST);

        PanningPanel3.setOpaque(false);
        PanningPanel3.setPreferredSize(new java.awt.Dimension(50, 30));
        PanningPanel3.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Panning");
        PanningPanel3.add(jLabel8, java.awt.BorderLayout.NORTH);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Speed");
        PanningPanel3.add(jLabel9, java.awt.BorderLayout.SOUTH);

        PanningPanel1.add(PanningPanel3, java.awt.BorderLayout.EAST);

        add(PanningPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        mouseEntered = true;
    }//GEN-LAST:event_formMouseEntered
    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        mouseEntered = false;
    }//GEN-LAST:event_formMouseExited

    private void zoomFactorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zoomFactorSliderStateChanged
       // OpenGLZoomer.ZOOMFACTOR = (float) this.zoomFactorSlider.getValue() / 40f;
        //this.SEARC_ZOOM_FACTOR = (float) this.zoomFactorSlider.getValue() / 20f;
}//GEN-LAST:event_zoomFactorSliderStateChanged

    private void panningFactorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panningFactorSliderStateChanged
      //  OpenGLCamera.MOVINGFACTOR = (float) this.panningFactorSlider.getValue() / 10f;
}//GEN-LAST:event_panningFactorSliderStateChanged

    private void jPanel1formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formMouseEntered

    private void jPanel1formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Buttons.CircularButton Control2D;
    public Buttons.CircularButton Control3D;
    public Buttons.CircularButton ControlDown;
    public Buttons.CircularButton ControlLeft;
    public Buttons.CircularButton ControlReset;
    public Buttons.CircularButton ControlRight;
    public Buttons.CircularButton ControlRotateLeft;
    public Buttons.CircularButton ControlRotateRight;
    public Buttons.CircularButton ControlUp;
    public Buttons.CircularButton ControlZoomIn;
    public Buttons.CircularButton ControlZoomOut;
    private javax.swing.JPanel ControlsPanel;
    private javax.swing.JPanel PanningPanel;
    private javax.swing.JPanel PanningPanel1;
    private javax.swing.JPanel PanningPanel3;
    private javax.swing.JPanel ZoomPanel;
    private javax.swing.JPanel ZoomingPanel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JSlider panningFactorSlider;
    public javax.swing.JSlider zoomFactorSlider;
    // End of variables declaration//GEN-END:variables
}
